-- MySQL Script generated by MySQL Workbench
-- Sun Jan  5 11:55:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8 ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`users` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`events` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `base_price` DOUBLE NOT NULL,
  `rating` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`auditoriums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`auditoriums` (
  `name` VARCHAR(25) NOT NULL,
  `amount_of_seats` BIGINT(5) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`vip_seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`vip_seats` (
  `auditoriums_name` VARCHAR(25) NOT NULL,
  `number` BIGINT(5) NOT NULL,
  PRIMARY KEY (`auditoriums_name`, `number`),
  INDEX `fk_vip_seats_auditoriums1_idx` (`auditoriums_name` ASC),
  CONSTRAINT `fk_vip_seats_auditoriums1`
    FOREIGN KEY (`auditoriums_name`)
    REFERENCES `cinema`.`auditoriums` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`event_has_auditoriums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`event_has_auditoriums` (
  `auditoriums_name` VARCHAR(25) NOT NULL,
  `air_date` DATETIME NOT NULL,
  `events_id` BIGINT(10) NOT NULL,
  PRIMARY KEY (`auditoriums_name`, `air_date`),
  INDEX `fk_auditoriums_has_event_auditoriums1_idx` (`auditoriums_name` ASC),
  INDEX `fk_auditoriums_has_event_events1_idx` (`events_id` ASC),
  CONSTRAINT `fk_auditoriums_has_event_auditoriums1`
    FOREIGN KEY (`auditoriums_name`)
    REFERENCES `cinema`.`auditoriums` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_auditoriums_has_event_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `cinema`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`orders` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NOT NULL,
  `users_id` BIGINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cinema`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`tickets` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `seat` BIGINT(10) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `orders_id` BIGINT(10) NULL,
  `event_has_auditoriums_auditoriums_name` VARCHAR(25) NOT NULL,
  `event_has_auditoriums_air_date` DATETIME NOT NULL,
  `users_id` BIGINT(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_orders1_idx` (`orders_id` ASC),
  INDEX `fk_tickets_event_has_auditoriums1_idx` (`event_has_auditoriums_auditoriums_name` ASC, `event_has_auditoriums_air_date` ASC),
  INDEX `fk_tickets_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_tickets_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `cinema`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_event_has_auditoriums1`
    FOREIGN KEY (`event_has_auditoriums_auditoriums_name` , `event_has_auditoriums_air_date`)
    REFERENCES `cinema`.`event_has_auditoriums` (`auditoriums_name` , `air_date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cinema`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`statistics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action` VARCHAR(45) NOT NULL,
  `amount` BIGINT(10) NOT NULL,
  `users_id` BIGINT(10) NULL,
  `events_id` BIGINT(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_satistics_users1_idx` (`users_id` ASC),
  INDEX `fk_satistics_events1_idx` (`events_id` ASC),
  CONSTRAINT `fk_satistics_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cinema`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_satistics_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `cinema`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`roles` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`users_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`users_has_roles` (
  `users_id` BIGINT(10) NOT NULL,
  `roles_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`users_id`, `roles_name`),
  INDEX `fk_roles_has_users_users1_idx` (`users_id` ASC),
  INDEX `fk_roles_has_users_roles1_idx` (`roles_name` ASC),
  CONSTRAINT `fk_roles_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cinema`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_users_roles1`
    FOREIGN KEY (`roles_name`)
    REFERENCES `cinema`.`roles` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
