version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: cinema
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - C:\\tomcat\mysql:/var/lib/mysql

  tomcat:
    image: tomcat:latest
    restart: always
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - C:\\Mariia\laba\target\kryvokin.war:/usr/local/tomcat/webapps/kryvokin.war
      - C:\\tomcat\logs:/usr/local/tomcat/logs
      - C:\\tomcat\config\server.xml:/usr/local/tomcat/conf/server.xml
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    command: "/usr/local/tomcat/bin/catalina.sh jpda run"